{ config, pkgs, ... }:
{
  environment.systemPackages = [
    pkgs.act
    pkgs.bat
    pkgs.curlie
    pkgs.duf
    pkgs.dust
    pkgs.eza
    pkgs.ffmpeg
    pkgs.fish
    pkgs.fzf
    pkgs.ggshield
    pkgs.git
    pkgs.gnupg
    pkgs.htop
    pkgs.hugo
    pkgs.localsend
    pkgs.mkalias
    pkgs.neovim
    pkgs.nixfmt-rfc-style
    pkgs.nodejs_22
    pkgs.obsidian
    pkgs.pipx
    pkgs.pyenv
    pkgs.rbenv
    pkgs.sshuttle
    pkgs.starship
    pkgs.stow
    pkgs.unzip
    pkgs.uv
    pkgs.vim
    pkgs.wget
    pkgs.zoxide
  ];
}
